### ISSUE TITLE
Failure to oversample with HAIS 50 P hall effect current sensor.

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/UKSC_BPS#2]
I was browsing the code and noticed that the loop through the "old" current sensor (50P)  does not match the loop for the "new" sensor (SCA100B). we read the ADC 1024 times, but then when we do read it, we are not incrementing result, only setting it. This causes us to loose only really know the value on the last sample, and possibly causes an error by a factor of 1024 in the ADC channel voltage. (and possibly an offset+scale error in the converted output)

This is not critical as we do not plan on using this current sensor, but it wouldn't hurt to address it at some point ;)

`for(k=0;k<1024;++k)
{
 	SetChanADC(ADC_CH0);	//channel has the current sensor value
 	ConvertADC();			//tell the ADC to run once
 	while(BusyADC());		//wait until the conversion is finished
 	result = ReadADC();	    //store the value that was converted into result
}`

**Comment by dcambron** [comment]
Yeah I noticed that the other day. Ill fix it when I come to town.

**Comment by cheintz** [comment]
Closed, removed the option for the old current sensor in favor of a DIP switch to force CBS to take place, regardless of the "normal" thresholds.

a121b80a53a06b8dd00cd0535aaee39456df8edb

Chris
