### ISSUE TITLE
Current Sensor and CBS stop reading after 32768 timer0 interrupts

### ISSUE THREAD

**Issue by dcambron** [KentuckySolarCar/UKSC_BPS#5]
The variables

glob_CBSDelay
glob_CURRENTDelay

in the master code are set to 16 bit ints and increment whenever timer0 interrupts. Thus they overflow to negative values after 32768 timer0 interrupts. This causes a comparison to do the wrong thing and thus current stops being read and CBS stops being done.

I suggest removing glob_CURRENTDelay altogether because it isn't actually being used. And then set glob_CBSDelay to an unsigned long (or change the comparison code so it isn't an issue)

We've never actually seen this issue until the other day when I set the interrupt frequency to 5.2 Hz, thus causing the problem to appear in a little under 2 hours as opposed to a little under 10 hours

**Comment by SenaitNuguse** [comment]
this is in masterBPS.c?

**Comment by dcambron** [comment]
masterBPS.c and masterBPS_management.c

**Comment by cheintz** [comment]
How bad is this for our test data?

Chris Heintz

**Comment by dcambron** [comment]
Only happened once, and it was very obvious by looking at the data. I don't
think any information was lost, since the variation of the current in that
time period is likely within the inaccuracy of the current sensor

**Comment by cheintz** [comment]
Closed, I did not remove the CurrentDelay variable as it still appeared to be used.

7af67b6e50ab255911cfc336498206a44af39339
