### ISSUE TITLE
Powerup transients result in incorrect current sensor zero

### ISSUE THREAD

**Issue by cheintz** [KentuckySolarCar/UKSC_BPS#7]
When zeroing the current sensor, the voltage transients associated with starting the system up by applying 5V power cause the current sensor to zero at [-1,1]A. Pushing the reset button with power applied brings this to within a few mA.

**Comment by dcambron** [comment]
Nice catch. When I tested it I was usually pressing the reset button so that makes sense

**Comment by cheintz** [comment]
Fix tested on bench. for LiPo testing and merged into main. Untested in main. 

5e43e9dea2c18721d8cc0953aee427d2571bed70
